### ISSUE TITLE
Bikeshedding: A better package name?

### ISSUE THREAD

**Issue by crstnbr** [MasonProtter/Gaius.jl#4]
Love the package(!) but not the name, to be honest. I think we can find something better!

I like the Caesar quote. If we want to relate to it, I'd prefer Caesar.jl over Gaius.jl.

Other names that came to my mind were Bolt.jl, a la [Usain Bolt](https://de.wikipedia.org/wiki/Usain_Bolt), the fastest man on the planet, and Sonic.jl, in reference to [Sonic the Hedgehog](https://en.wikipedia.org/wiki/Sonic_the_Hedgehog_(character)). But I'll try to think about further alternatives.

**Comment by crstnbr** [comment]
Ahh just realized that Caesar.jl is already taken.

**Comment by MasonProtter** [comment]
Yeah, I was originally going to call it LoopVectorizationBLAS.jl, but I felt like that was a little too long and perhaps not very meaningful since it would be unusual for a BLAS to *not* use loops and vectorization. 

Then I thought maybe I could play off the Divide and Conquer strategy and name it after some general, and then I fixated on Julius Caesar, but Caesar.jl was already taken and Julius.jl seemed a little weird.

Definitely open to changing the name.

**Comment by chriselrod** [comment]
> I was originally going to call it LoopVectorizationBLAS.jl

Aside from also being a little long, packages with names ending in capitol letters wont be automatically approved once you're ready to register it. I was able to get `VectorizedRNG` registered without a problem, since RNG is a well known acronym, but `MKL.jl` ran into problems. I think as far as acronyms go, `BLAS` is closer to `MKL` than it is to `RNG` in terms of how well known it is.

On naming packages after algorithms, if you were to try an approach other than a divide and conquer recursive algorithm, would you create a new package, or place the code here?

**Comment by crstnbr** [comment]
Why not something explicit like  BasicLinearAlgebra.jl? This would be in the spirit of the Julia guideline to avoid acronyms. It would also look nice next to GenericLinearAlgebra.jl.

**Comment by MasonProtter** [comment]
> On naming packages after algorithms, if you were to try an approach other than a divide and conquer recursive algorithm, would you create a new package, or place the code here?

Valid point. The naming was totally post-hoc. 

> Why not something explicit like BasicLinearAlgebra.jl? This would be in the spirit of the Julia guideline to avoid acronyms. It would also look nice next to GenericLinearAlgebra.jl.

Yeah, that's a definite option. I don't like how long it is to type, especially because this isn't a package that exports names (maybe I should change that?). 

I chose Gaius initially as a throw-away name but I must admit I've grown a little attached to it. In that case it's maybe better that I change the name sooner than later.

**Comment by MasonProtter** [comment]
I think after chatting with some people about this, I'm going to stick with Gaius.jl for now and then if this ever gets to a state where it's usable and reliable enough for people to actually consider using it, I'll rename it to something like `GenericLinearAlgebra.jl`. 

I think it's best to not push out things with 'official' sounding names if it's not really ready to be used officially and if I'm not sure if I'll end up maintaining it long-term.

**Comment by sosiristseng** [comment]
FWIW, the name `GenericLinearAlgebra.jl` is [taken](https://github.com/JuliaLinearAlgebra/GenericLinearAlgebra.jl) by JuliaLinearAlgebra.

**Comment by DilumAluthge** [comment]
Closed by https://github.com/JuliaRegistries/General/pull/26665
